Repository QuantEcon/lecture-python-intro, pull requests merged in 2024-04, with the labels that each got.

#384 [inequality] Review of lecture and incorporate updates
  lectures/_config.yml
  lectures/_static/lecture_specific/inequality/usa-gini-nwealth-tincome-lincome.csv
  lectures/inequality.md
Labels: ready, review

#387 Address comments for `cagan_ree` lecture
  lectures/cagan_ree.md
Labels: ready

#330 Use map instead of applymap
  lectures/inflation_history.md
Labels: future

#423 [markov_chains_II] MAINT: Update example4 graphviz figure
  .gitignore
  lectures/_static/lecture_specific/graphviz/graphviz_generation.ipynb
  lectures/_static/lecture_specific/markov_chains_II/example4.png
Labels: ready
