Repository QuantEcon/lecture-python-intro, pull requests merged in 2024-02, with the labels that each got.

#332 Typos in solow.md
  lectures/solow.md
Labels: ready

#342 Update `long_run_growth` Lecture
  lectures/_static/lecture_specific/long_run_growth/tooze_ch1_graph.png
  lectures/long_run_growth.md
Labels: ready

#356 MAINT: enable latex in the cache build environment for sympy rendering
  .github/workflows/cache.yml
Labels: ready

#279 Update solutions in lecutre pv
  lectures/pv.md
Labels: in-work

#370 ENH: move inflation_history to economic data
  .github/workflows/ci.yml
  lectures/_toc.yml
  lectures/inflation_history.md
Labels: ready

#369 [business_cycle] Update Variable Name for Industrial Output
  lectures/business_cycle.md
Labels: ready

#362 ENH: update show code cell prompt to be more concise
  lectures/_config.yml
Labels: ready

#360 MAINT: use jupyter builder to filter header for download notebook
  lectures/geom_series.md
Labels: ready, maintenance

#372 [intro_supply_demand] Adding to supply and demand lecture
  lectures/intro_supply_demand.md
Labels: improve

#376 [cons_smooth] Update consumption smoothing lecture
  lectures/cons_smooth.md
Labels: improve

#378 [simple_linear_regression] Review pandas code, update spelling (american), and misc edits
  lectures/simple_linear_regression.md
Labels: ready

#377 ENH: Adjustments to TOC (two parts for linear dynamics, rework essential tools)
  lectures/_toc.yml
Labels: ready
